version: "2"
run:
  concurrency: 4
  tests: true
linters:
  enable:
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - durationcheck
    - gocritic
    - gosec
    - gosmopolitan
    - loggercheck
    - makezero
    - mirror
    - nilerr
    - noctx
    - predeclared
    - revive
    - unconvert
  settings:
    gocritic:
      disabled-checks:
        - singleCaseSwitch
        - assignOp
        - ifElseChain
    revive:
      rules:
        - name: unused-parameter
          disabled: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
